#:schema node_modules/wrangler/config-schema.json
name = "serebii-webhook"
main = "source/index.ts"
compatibility_date = "2024-11-12"

[triggers]
crons = ["0 * * * *"]

[observability]
enabled = true

[[d1_databases]]
binding = "database"
database_name = "serebii-webhook"
database_id = "207a8b9e-b0e6-4e1e-87ce-74fe308fda05"

[[queues.producers]]
queue = "serebii-webhook"
binding = "queue"

[[queues.consumers]]
queue = "serebii-webhook"
max_batch_size = 100
max_concurrency = 1
retry_delay = 5
